name: "build-release"

on:
  push:
    paths: 
      - '**.rs'
      - '**.lock'
      - '**.toml'
      - '**.yml'
    branches:
      - "master"

jobs:
  build-release:
    name: "Build & Release"
    runs-on: "windows-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set current version"
        run: echo "GIT_VERSION=$(git.exe rev-parse --short HEAD)" >> $env:GITHUB_ENV

      - name: "Build Yakuza 0"
        run: |
          cargo.exe build -p yakuza0 --release

      - name: "Build Yakuza Kiwami"
        run: |
          cargo.exe build -p kiwami --release

      - name: "Build Yakuza Kiwami 2"
        run: |
          cargo.exe build -p kiwami2 --release

      - name: "Build Yakuza Like a Dragon"
        run: |
          cd likeadragon/lib
          cargo.exe build --release --features non_automatic
          cd ../../
          cd likeadragon/injector
          cargo.exe build --release
          cd ../../

      - name: "Pack Yakuza Like a Dragon build"
        run: |
          Copy target/release/likeadragon.dll ./likeadragon.dll
          Copy target/release/likeadragon-freecam.exe ./likeadragon-freecam.exe
          tar.exe -a -c -f likeadragon-freecam.zip likeadragon.dll likeadragon-freecam.exe

      - name: "Automatic Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            target/release/yakuza0-freecam.exe
            target/release/kiwami-freecam.exe
            target/release/kiwami2-freecam.exe
            likeadragon-freecam.zip

