name: "build-release"

on:
  push:
    paths: 
      - '**.rs'
      - '**.lock'
      - '**.toml'
    branches:
      - "master"
      - "dev"

jobs:
  build-release:
    name: "Build & Release"
    runs-on: "windows-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      # ...
      - name: "Build Yakuza 0"
        run: |
          cargo.exe build -p yakuza0 --release

      - name: "Build Yakuza Kiwami"
        run: |
          cargo.exe build -p kiwami --release

      - name: "Build Yakuza Kiwami 2"
        run: |
          cargo.exe build -p kiwami2 --release

      - name: "Automatic Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            target/release/*.exe

